applications:
  - name: django-app
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/EssenceMaks/GoIT_DevOps.git # UPDATE THIS
      targetRevision: HEAD
      path: charts/django-app
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories: []
#  - name: my-repo
#    url: https://github.com/my-user/my-repo.git
#    username: my-user
#    password: my-password
