pipeline {
    agent {
        kubernetes {
            defaultContainer 'kaniko'
            yaml '''
apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
  labels:
    jenkins: kaniko
spec:
  serviceAccountName: jenkins
  securityContext:
    runAsUser: 0
    fsGroup: 0
  containers:
  - name: jnlp
    env:
    - name: JENKINS_URL
      value: "http://jenkins.jenkins.svc.cluster.local:8080"
    - name: JENKINS_TUNNEL
      value: "jenkins-agent.jenkins.svc.cluster.local:50000"
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.16.0-debug
    imagePullPolicy: Always
    command:
    - sleep
    args:
    - 99d
    env:
    - name: AWS_SDK_LOAD_CONFIG
      value: "true"
'''
        }
    }

    environment {
        registry = "${ECR_REPOSITORY_URL}"
        registryCredential = 'ecr-credentials'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build and Push') {
            steps {
                container('kaniko') {
                    withCredentials([usernamePassword(credentialsId: registryCredential, usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                        script {
                            // Extract repo URL logic if needed, but Kaniko handles full URLs
                            // ECR_REPOSITORY_URL is expected to be full URI like 123456.dkr.ecr.region.amazonaws.com/repo
                            
                            sh '''
                                /kaniko/executor \
                                    --context $(pwd)/Django \
                                    --dockerfile $(pwd)/Django/Dockerfile \
                                    --destination ${registry}:${BUILD_NUMBER} \
                                    --destination ${registry}:latest \
                                    --cache=true
                            '''
                        }
                    }
                }
            }
        }
    }
}
