pipeline {
    agent any

    environment {
        registry = "${ECR_REPOSITORY_URL}" // This variable should be set in Jenkins
        registryCredential = 'ecr-credentials' // Jenkins credential ID
        dockerImage = ''
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Building image') {
            steps {
                script {
                    dockerImage = docker.build(registry + ":$BUILD_NUMBER", "./Django")
                }
            }
        }

        stage('Pushing to ECR') {
            steps {
                script {
                    docker.withRegistry('https://' + registry.split('/')[0], "ecr:eu-central-1:" + registryCredential) {
                        dockerImage.push()
                        dockerImage.push('latest')
                    }
                }
            }
        }
    }
}
