pipeline {
    agent any

    environment {
        registry = "${ECR_REPOSITORY_URL}" // This variable should be set in Jenkins
        registryCredential = 'ecr-credentials' // Jenkins credential ID
        dockerImage = ''
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Building image') {
            steps {
                script {
                    dockerImage = docker.build(registry + ":$BUILD_NUMBER", "./Django")
                }
            }
        }

        stage('Pushing to ECR') {
            steps {
                script {
                    docker.withRegistry('https://' + registry.split('/')[0], "ecr:eu-central-1:" + registryCredential) {
                        dockerImage.push()
                        dockerImage.push('latest')
                    }
                }
            }
        }

        stage('Deploy to EKS') {
            steps {
                script {
                    // Assuming kubectl is configured on Jenkins agent or use a k8s plugin
                    // Update the image tag in the helm chart values or set it during upgrade
                    sh "helm upgrade --install django-app ./charts/django-app --set image.repository=${registry} --set image.tag=$BUILD_NUMBER --namespace default"
                }
            }
        }
    }
}
