# Отключаем тяжелые компоненты, без которых можно жить
alertmanager:
  enabled: false

prometheus-node-exporter:
  enabled: true

# Ужимаем Графану
grafana:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi
  persistence:
    enabled: false # Чтобы не возиться с дисками

# Ужимаем сам Прометеус
prometheus:
  prometheusSpec:
    retention: 2d
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 1Gi
    storageSpec:
      emptyDir:
        sizeLimit: 2Gi
