controller:
  componentName: "jenkins-controller"
  image:
    registry: "docker.io"
    repository: "jenkins/jenkins"
    tag: "lts"
  imagePullPolicy: "Always"
  numExecutors: 2
  
  installPlugins:
    - kubernetes:4306.vc91e951ea_eb_d
    - workflow-aggregator:596.v8c21c963d92d
    - git:5.2.1
    - configuration-as-code:2006.v001a_2ca_6b_574
    - docker-workflow:580.vc0c340686b_54

  # Security context to allow writing to the volume
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
    
  containerSecurityContext:
    runAsUser: 1000
    readOnlyRootFilesystem: false
  
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1024Mi"
      
  service:
    type: ClusterIP
    port: 8080
    
persistence:
  enabled: true
  storageClass: "gp2"
  size: "8Gi"
