replicaCount: 1

image:
  repository: 794531974301.dkr.ecr.eu-central-1.amazonaws.com/final-project-repo
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

env:
  DJANGO_ENV: "production"
  DATABASE_HOST: ""
  DATABASE_NAME: ""
  DATABASE_USER: ""
  DATABASE_PASSWORD: ""
